[package]
name = "graphile_worker_task_handler"
version = "0.5.4"
edition = "2021"
license-file = "LICENSE.md"
description = "A library to handle tasks for the Graphile Worker project"
homepage = "https://docs.rs/graphile_worker_task_handler"
documentation = "https://docs.rs/graphile_worker_task_handler"
repository = "https://github.com/leo91000/graphile_worker/crates/graphile_workers_task_handler"
keywords = []
categories = []
readme = "README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
graphile_worker_ctx = { path = "../ctx", version = "0.2.4" }
serde.workspace = true
serde_json.workspace = true
tokio = { workspace = true, features = ["rt", "macros"] }
tokio-util.workspace = true

[dev-dependencies]
anyhow.workspace = true
