[package]
name = "archimedes_task_handler"
version = "0.2.0"
edition = "2021"
license-file = "LICENSE.md"
description = "A library to handle tasks for the Archimedes project"
homepage = "https://docs.rs/archimedes_task_handler"
documentation = "https://docs.rs/archimedes_task_handler"
repository = "https://github.com/leo91000/archimedes/crates/archiemedes_task_handler"
keywords = []
categories = []
readme = "README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { workspace = true }
tokio = { workspace = true, features = ["rt", "macros"] }
tokio-util = { workspace = true }

[dev-dependencies]
anyhow = { workspace = true }
