[package]
name = "archimedes_shutdown_signal"
version = "0.3.0"
edition = "2021"
license = "MIT"
description = "Migrations package for archimedes, a high performance Rust/PostgreSQL job queue"
homepage = "https://docs.rs/archimedes_shutdown_signal"
documentation = "https://docs.rs/archimedes_shutdown_signal"
repository = "https://github.com/leo91000/archimedes/crates/shutdown_signal"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cfg-if = { workspace = true }
futures = { workspace = true }
tokio = { workspace = true, features = ["signal", "macros"] }
tracing = { workspace = true }
