[package]
name = "graphile_worker_task_details"
version = "0.1.0"
edition = "2021"
license-file = "LICENSE.md"
description = "Task details for graphile_worker, mapping task IDs to identifiers"
homepage = "https://docs.rs/graphile_worker"
documentation = "https://docs.rs/graphile_worker"
repository = "https://github.com/leo91000/graphile_worker"
readme = "README.md"

[dependencies]
tokio = { workspace = true, features = ["sync"] }
tracing.workspace = true
